name: absensi_mobile
description: Aplikasi Absensi Digital Mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Routing
  get: ^4.6.5
  get_storage: ^2.1.1

  # API & Networking
  dio: ^5.3.2

  # Camera & Image
  image_picker: ^1.0.4
  camera: ^0.10.5+4

  # Geolocation (GPS)
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Firebase (Push Notification)
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

  # UI
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1

  # Utilities
  intl: ^0.18.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
